apiVersion: apps/v1
kind: Deployment
metadata:
  name: overops-storage-server-deployment
  labels:
    app: overops-storage-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overops-storage-server
  template:
    metadata:
      labels:
        app: overops-storage-server
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000     
      containers:
        - name: overops-storage-server
          image: overops/storage-server-s3:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /opt/takipi-storage/private
              name: overops-storage-private-volume
      volumes:
        - name: overops-storage-private-volume
          secret:
            secretName: overops-storage
---
kind: Service
apiVersion: v1
metadata:
  name: overops-storage-service
spec:
  selector:
    app: overops-storage-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
