apiVersion: v1
kind: Pod
metadata:
  name: event-generator-sidecar-pod
spec:
  volumes:
  - name: overops-agent
    emptyDir: {}
  initContainers:
    - name: overops-agent
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      image: overops/agent-sidecar:latest
      imagePullPolicy: Always
      volumeMounts:
      - name: overops-agent
        mountPath: /takipi
  containers:
    - name: event-generator
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      image: 432746435694.dkr.ecr.us-east-1.amazonaws.com/event-generator:no-flags
      imagePullPolicy: Always
      resources:
        requests:
          cpu: "100m"
          memory: "1Gi"
        limits:
          cpu: "1000m"
          memory: "2Gi"
      env:
      - name: TAKIPI_COLLECTOR_HOST
        value: "overops-collector-service"
      - name: TAKIPI_COLLECTOR_PORT
        value: "6060"
      - name: JAVA_TOOL_OPTIONS
        value: "-agentpath:/takipi/lib/libTakipiAgent.so=takipi.application.name=EventGeneratorSidecar,takipi.deployment.name=v2.1.3.sidecar"
      volumeMounts:
      - name: overops-agent
        mountPath: /takipi
