apiVersion: apps/v1
kind: Deployment
metadata:
  name: overops-collector-deployment
  labels:
    app: overops-collector
spec:
  replicas: 2
  selector:
    matchLabels:
      app: overops-collector
  template:
    metadata:
      labels:
        app: overops-collector
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000     
      containers:
        - name: overops-collector
          image: overops/collector:latest
          ports:
            - containerPort: 6060
          volumeMounts:
            - mountPath: /opt/takipi/private
              name: overops-private-volume
          imagePullPolicy: Always
          resources:
            requests:
              cpu: "100m"
              memory: "1Gi"
            limits:
              cpu: "1000m"
              memory: "2Gi"
      volumes:
        - name: overops-private-volume
          secret:
            secretName: overops-collector
---
kind: Service
apiVersion: v1
metadata:
  name: overops-collector-service
spec:
  selector:
    app: overops-collector
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
